name: Build & Deploy on EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy-on-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e

            # 1) Clone or update your app
            if [ ! -d ~/app ]; then
              git clone git@github.com:kittitater/RandomTopMovie.git ~/app
            fi
            cd ~/app
            git fetch origin
            git reset --hard origin/main

            # 2) Debug: List files to verify presence of serve_model_API.py
            ls -l ~/app

            # 3) Log Docker version for debugging
            docker --version

            # 4) Build the new Docker image
            docker build -t license-censor-api:latest . || { echo "Docker build failed"; cat requirements.txt; ls -l; exit 1; }

            # 5) Stop & remove old container if running
            docker rm -f ml-model || true

            # 6) Run the new container
            docker run -d \
              --name ml-model \
              -p 127.0.0.1:3000:80 \
              license-censor-api:latest

            # 7) Log container status
            docker ps -a

            # 8) Prune only dangling images
            docker image prune -f